export const locations: string[] = [
    "Remote",
    "New York, USA",
    "London, UK",
    "Tokyo, Japan",
    "Paris, France",
    "Berlin, Germany",
    "Sydney, Australia",
    "Toronto, Canada",
    "San Francisco, USA",
    "Los Angeles, USA",
    "Chicago, USA",
    "Austin, USA",
    "Seattle, USA",
    "Boston, USA",
    "Singapore, Singapore",
    "Hong Kong, Hong Kong",
    "Dubai, UAE",
    "Amsterdam, Netherlands",
    "Dublin, Ireland",
    "Zurich, Switzerland",
    "Copenhagen, Denmark",
    "Stockholm, Sweden",
    "Oslo, Norway",
    "Helsinki, Finland",
    "Vancouver, Canada",
    "Montreal, Canada",
    "Melbourne, Australia",
    "Auckland, New Zealand",
    "Seoul, South Korea",
    "Beijing, China",
    "Shanghai, China",
    "Mumbai, India",
    "Bangalore, India",
    "São Paulo, Brazil",
    "Buenos Aires, Argentina",
    "Mexico City, Mexico",
    "Madrid, Spain",
    "Barcelona, Spain",
    "Rome, Italy",
    "Milan, Italy",
    "Vienna, Austria",
    "Prague, Czech Republic",
    "Warsaw, Poland",
    "Moscow, Russia",
    "Tel Aviv, Israel",
    "Johannesburg, South Africa",
    "Cairo, Egypt",
    "Nairobi, Kenya",
    "Lagos, Nigeria"
];
